#!/usr/local/bin/zsh

# Upgrade Repository
function uprepos() {
    for tool in $1; do
        if [ -d $tool ]; then
        echo -e "\nUpdating $(basename $tool)"
            cd $tool
            git pull
        fi
    done
}
