#!/usr/local/bin/zsh

# vm
function vm() {
    
    case $1 in
        list)
            \ls $VIRTUALMACHINES | awk '{print substr($1, 1, length($1)-9)}'
            ;;
        *)
            vmx=$VIRTUALMACHINES/$1.vmwarevm/$1.vmx
            if [ -f $vmx ]; then
                case $2 in
                    delete)
                        vmrun -T fusion delete $vmx
                        ;;
                    copyfrom)
                        scp clownfire@$(vmrun -T fusion getGuestIPAddress $vmx -wait):$3 $4
                        ;;
                    copyto)
                        scp $3 clownfire@$(vmrun -T fusion getGuestIPAddress $vmx -wait):$4
                        ;;
                    start)
                        vmrun -T fusion start $vmx nogui
                        vmrun -T fusion enableSharedFolders $vmx
                        ssh clownfire@$(vmrun -T fusion getGuestIPAddress $vmx -wait)
                        ;;
                    ssh)
                        ssh clownfire@$(vmrun -T fusion getGuestIPAddress $vmx -wait)
                        ;;
                    stop)
                        vmrun -T fusion stop $vmx soft
                        ;;
                    snap)
                        case $3 in
                            list)
                                vmrun -T fusion listSnapshots $vmx showtree
                                ;;
                            save)
                                vmrun -T fusion snapshot $vmx $4
                                ;;
                            restore)
                                vmrun -T fusion revertToSnapshot $vmx $4
                                ;;
                            delete)
                                vmrun -T fusion deleteSnapshot $vmx $4
                                ;;
                            *)
                                echo "ERRORE"
                                ;;
                        esac
                        ;;
                    *)
                        echo "ERRORE"
                        ;;
                esac
            fi
    esac
}
